model_dir: '/home/lukas/projects/brainmagick/bm/runs/no_meta_simple_conv_128_shot_128_way_v1/best_checkpoint_3_426.pth'
# ks: [1, 5, 15, 50, 500, 1500]
ks: [1, 5, 15, 50]

dset: 
  mini_batches_per_trial: 8
  samples_per_mini_batch: 64
  batch_size: 1
  unfreeze_encoder_on_support: False
  n_shot: 4
  split_strategy: 'recording'