model_dir: '/home/lukas/projects/brainmagick/bm/runs/no_meta_simple_conv_32_shot_32_way_v20/best_checkpoint_0_21.pth'
ks: [1, 5, 15]

dset: 
  mini_batches_per_trial: 8
  samples_per_mini_batch: 32
  batch_size: 1
  unfreeze_encoder_on_support: False
  n_shot: 4
  split_strategy: 'recording'