model_dir: '/home/lukas/projects/brainmagick/bm/runs/no_meta_simple_conv_512_shot_512_way_v2/best_checkpoint_0_209.pth'
ks: [1, 5, 15, 50]

dset: 
  mini_batches_per_trial: 8
  samples_per_mini_batch: 128
  batch_size: 1
  unfreeze_encoder_on_support: False
  n_shot: 4
  split_strategy: 'recording'