# @package _global_

meta_train:
  delta: 0.0001
  meta_epochs: 20
  split_strategy: 'recording'
  do_meta_train: False

  train:
    mini_batches_per_trial: 1
    samples_per_mini_batch: 128
    batch_size: 1

  val:
    mini_batches_per_trial: 1
    samples_per_mini_batch: 128
    batch_size: 1