# @package _global_

meta_train:
  delta: 0.0001
  meta_epochs: 20
  split_strategy: 'session'
  do_meta_train: True

  train:
    mini_batches_per_trial: 4
    samples_per_mini_batch: 128
    batch_size: 4

  val:
    mini_batches_per_trial: 4
    samples_per_mini_batch: 128
    batch_size: 4